### ISSUE TITLE
Build of 0.3.0 fails: failed to run custom build command for `openssl-sys v0.9.54`

### ISSUE THREAD

**Issue by yurivict** [cryptoballot/cryptoballot#13]
```
     Running `/usr/local/bin/rustc --edition=2018 --crate-name rand_core /usr/ports/misc/cryptoballot/work/cryptoballot-0.3.0/cargo-crates/rand_core-0.5.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=2 --cfg 'feature="alloc"' --cfg 'feature="getrandom"' --cfg 'feature="std"' -C metadata=7a0f85a495aeaaa0 -C extra-filename=-7a0f85a495aeaaa0 --out-dir /usr/ports/misc/cryptoballot/work/target/release/deps -L dependency=/usr/ports/misc/cryptoballot/work/target/release/deps --extern getrandom=/usr/ports/misc/cryptoballot/work/target/release/deps/libgetrandom-f34ad183af1c0300.rmeta --cap-lints allow -C linker=cc -C link-arg=-fstack-protector-strong`
error: failed to run custom build command for `openssl-sys v0.9.54`

Caused by:
  process didn't exit successfully: `/usr/ports/misc/cryptoballot/work/target/release/build/openssl-sys-09a5fd54fd923598/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_FREEBSD_OPENSSL_LIB_DIR
X86_64_UNKNOWN_FREEBSD_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR = 
cargo:rerun-if-env-changed=X86_64_UNKNOWN_FREEBSD_OPENSSL_INCLUDE_DIR
X86_64_UNKNOWN_FREEBSD_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR = 

--- stderr
thread 'main' panicked at 'OpenSSL library directory does not exist: ', /usr/ports/misc/cryptoballot/work/cryptoballot-0.3.0/cargo-crates/openssl-sys-0.9.54/build/main.rs:52:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `zmq-sys v0.11.0`
```

FreeBSD 12

The environment variable TARGET=/usr/lib was specified.

**Comment by phayes** [comment]
Thanks for this!

I'll dig through the dependencies to see what is depending on OpenSSL.

**Comment by phayes** [comment]
Hi @yurivict ,

I've removed the OpenSSL requirement.

Because of the dependency on sawtooth, `cryptoballot_cli` and `cryptoballot_sawtooth_tp` both currently require ZeroMQ and Protoc.  I've added installation instructions on the README.md. 

I'm actually not satisfied with this requirement, and will work on removing these dependencies (from `cryptoballot_cli` at least).     I'll leave this issue open until I've fixed this.

**Comment by yurivict** [comment]
It still fails:
error: failed to run custom build command for `openssl-sys v0.9.54`

**Comment by phayes** [comment]
OK I think I got it figured out this time. 

I had to re-implement ECIES, removing the dependency on the `ecies` crate and implementing our own ed25519 version on ECIES.

This is now fixed on the crate in version `0.4.0`, but still exists on in the CLI and the transaction-processor (neither of which are posted to crates.io yet).

**Comment by yurivict** [comment]
The build still fails
```
     Running `/usr/ports/misc/cryptoballot/work/target/release/build/rust-crypto-6aa2e96ad8566962/build-script-build`
     Running `/usr/local/bin/rustc --crate-name num_traits /usr/ports/misc/cryptoballot/work/cryptoballot-0.4.0-1-g216fd14/cargo-crates/num-traits-0.2.11/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=2 --cfg 'feature="default"' --cfg 'feature="i128"' --cfg 'feature="std"' -C metadata=40bb0bc9640db939 -C extra-filename=-40bb0bc9640db939 --out-dir /usr/ports/misc/cryptoballot/work/target/release/deps -L dependency=/usr/ports/misc/cryptoballot/work/target/release/deps --cap-lints allow -C linker=cc -C link-arg=-fstack-protector-strong --cfg has_i128`
     Running `/usr/ports/misc/cryptoballot/work/target/release/build/secp256k1-7636fc8cb96fe84f/build-script-build`
     Running `/usr/ports/misc/cryptoballot/work/target/release/build/openssl-sys-09a5fd54fd923598/build-script-main`
error: failed to run custom build command for `openssl-sys v0.9.54`

Caused by:
  process didn't exit successfully: `/usr/ports/misc/cryptoballot/work/target/release/build/openssl-sys-09a5fd54fd923598/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_FREEBSD_OPENSSL_LIB_DIR
X86_64_UNKNOWN_FREEBSD_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR = 
cargo:rerun-if-env-changed=X86_64_UNKNOWN_FREEBSD_OPENSSL_INCLUDE_DIR
X86_64_UNKNOWN_FREEBSD_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR = 

--- stderr
thread 'main' panicked at 'OpenSSL library directory does not exist: ', /usr/ports/misc/cryptoballot/work/cryptoballot-0.4.0-1-g216fd14/cargo-crates/openssl-sys-0.9.54/build/main.rs:52:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

I guess it's because some parts aren't fixed yet, as you've mentioned.

**Comment by phayes** [comment]
@yurivict . 

You should be able to ONLY build the core cryptoballot library like so:

```
git clone git@github.com:ocudigital/opticalgym.git
cd cryptoballot/cryptoballot
cargo build
```

of course, it doesn't get you much, since it's only the core library (meant to be integrated into other projects), but that at least should be free of openSSL.   I'll be able to eventually remove the openssl requirement from `cryptoballot_cli`, but it's likely there for good for the transaction processor (unless we can convince the sawtooth folks to remove it from the sawtooth-sdk).

**Comment by phayes** [comment]
Aha!

Figured it out, it was lingering in `Cargo.lock`. 

```
> cargo tree --invert --package openssl-sys
Error: no crates found for package `openssl-sys`
```

**Comment by yurivict** [comment]
OpenSSL is installed, I'm not sure why can't it find it.
